### ISSUE TITLE
NPv1.1.2 - Netherite shulker box cannot be undyed in cauldron

### ISSUE THREAD

**Issue by rxay579** [OroArmor/Netherite-Plus-Mod#10]
A vanilla dyed shulker box can be undyed by right clicking in a cauldron (https://minecraft.gamepedia.com/Shulker_Box#Undyeing).

The netherite shulker boxes in this mod don't seem to have this functionality, though it does appear that they can be redyed a different color.

**Comment by OroArmor** [comment]
fixed with https://github.com/OroArmor/Netherite-Plus-Mod/commit/201ed5dc8f99650ab7c4c0c2a81af53a057b1db3
