### ISSUE TITLE
Forge - Bug/Issue

### ISSUE THREAD

**Issue by CloWnicide** [OroArmor/Netherite-Plus-Mod#103]
**Describe the bug**
CTD while loading

Crash log: https://gist.github.com/CloWnicide/b94decbedee8d4b657d59dbf8614ba76

**Comment by Hir0shiyt** [comment]
U have like 300 mods maybe there are mods that isn't compatible with netherite plus

"I think"

**Comment by OroArmor** [comment]
no its a forge issue

**Comment by CloWnicide** [comment]
Can confirm when I updated to 36.1.2 of Forge is when the issue started. Worked perfectly fine before then.
