### ISSUE TITLE
FORGE : Trident Rendering

### ISSUE THREAD

**Issue by WelpSTudent** [OroArmor/Netherite-Plus-Mod#104]
**Describe the bug**
A clear and concise description of what the bug is. Please indicate which mod platform you are using.
![image](https://user-images.githubusercontent.com/63996164/113723754-aa005300-96bf-11eb-8f6d-5280b2d32154.png)

FORGE
**To Reproduce**
Steps to reproduce the crash/bug

**Expected behavior**
be in my hand
**Screenshots**
![image](https://user-images.githubusercontent.com/63996164/113723832-bc7a8c80-96bf-11eb-9ee1-d539eeeef704.png)

**Comment by OroArmor** [comment]
This one was painful to fix.
