### ISSUE TITLE
my modpack isn't working and it has your mod in it

### ISSUE THREAD

**Issue by reasonableuser** [OroArmor/Netherite-Plus-Mod#105]
this is the full mod list including mod name mod author and name of mod file Good luck reading the entire thing
[FABRIC] Bedrock Breaker
Nierot
bedrock-breaker-1.0.jar
[Fabric] Expanded Storage
NinjaPhenix
expandedstorage-5.6.33+1.16.5.jar
Actually Unbreaking [Fabric]
WUTDAHACK
actuallyunbreaking-1.16.5-0.4.0.jar
Alloy Forgery
LordDeatHunter
wraith-alloy_forgery-1.0.8.jar
Architectury API (Fabric)
shedaniel
architectury-1.10.139-fabric.jar
Astromine: Complete
bolkor_
astromine-1.11.5+fabric-1.16.5.jar
AutoSwitch [Fabric]
Deximus_Maximus
autoswitch-3.1.0.jar
BackpackMod
SpyMan1736
backpackmod-1.16-1.3.1.jar
Basic Nether Ores [Forge/Fabric]
cScotPlay
BasicNetherOres-1.16.5-5.5.0.jar
Bedspreads (Fabric)
TheIllusiveC4
bedspreads-fabric-1.3.1-1.16.4.jar
Beenfo
Giselbaer
beenfo-1.16.5-fabric0.30.0-1.3.jar
Better Dropped Items
Draylar1
betterdroppeditems-1.2.4-1.16.2.jar
Better Hoppers (Hopper+) {FABRIC | FORGE}
Flytre7
better-hoppers-2.2.0.jar
Better Than Mending
legobmw99
BetterThanMending-1.6.0.jar
Biome Locator
Flytre7
biome_locator-1.1.2.jar
Bow Infinity Fix
Parker8283
BowInfinityFix-1.16.x-rv9.1.jar
Caelus API (Fabric)
TheIllusiveC4
caelus-fabric-0.0.15-1.16.4.jar
Campanion
wyn_price
campanion-1.3.5.jar
cAn i MiNe thIS bLOCk?
shedaniel
can-i-mine-this-block-1.0.2.jar
Carrier
GabrielHOlv
carrier-1.7.5.jar
Chains-Link
Lettas_
chains-link-1.16.2-2.0.1.jar
Cloth API (Fabric)
shedaniel
cloth-api-1.4.9.jar
Cloth Config API (Fabric)
shedaniel
cloth-config-4.11.19-fabric.jar
Colytra (Fabric)
TheIllusiveC4
colytra-fabric-1.3.0-1.16.4.jar
Comforts (Fabric)
TheIllusiveC4
comforts-fabric-0.0.2-1.16.5.jar
Controlling for Fabric
Jaredlll08
Controlling-For-Fabric-1.1.3.jar
Cosmetic Armor [FABRIC]
Apace100
cosmetic-armor-1.0.0.jar
Crawl (Fabric)
fewizz_
crawl-0.8.2.jar
Crimson Moon
Draylar1
crimson-moon-2.0.4-1.16.5.jar
Croptopia [FABRIC/FORGE]
thethonk
Croptopia-1.16.4-5-FABRIC-1.3.3.jar
Curios API (Fabric)
TheIllusiveC4
curios-fabric-0.0.13-1.16.5.jar
Curious Elytra (Fabric)
TheIllusiveC4
curiouselytra-fabric-1.1.1-1.16.5.jar
Curious Shulker Boxes (Fabric)
TheIllusiveC4
curiousshulkerboxes-fabric-1.1.1-1.16.5.jar
DragonLoot
pois1xlive
dragonloot-1.0.5.jar
Draylar's Battle Towers
Draylar1
battletowers-3.3.4-1.16.4.jar
Dropz
LazuriteTeam
dropz-1.1.3.jar
Dynamic FPS
juliand665
dynamic-fps-2.0.1.jar
EasierVillagerTrading
Giselbaer
easiervillagertrading-1.16.5-fabric0.30.0-1.5.4.jar
Enchanted ToolTips
Kyrptonaught
EnchantedToolTips-1.3.4-1.16.jar
Enhancement (Fabric)
shankn
enhancement-fabric-0.7.0.jar
Extra Alchemy
zabi94
extraalchemy-fabric-1.16.5-1.4.3.jar
Extra Origins
MoriyaShiine
extraorigins-1.16.5-10.jar
Fabric API
modmuss50
fabric-api-0.32.5+1.16.jar
Fabric Capes
VictorKohler
capes-1.1.1.jar
Fabric Language Kotlin
modmuss50
fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar
Fabric Loot Crates
DaFuqsy
lootcrates-1.0.0.jar
Fabricated Lucky Blocks
Draylar1
lucky-blocks-1.0.0-1.16.5.jar
Fabrishot
ramidzkh
fabrishot-1.3.0.jar
Falling Leaves (Fabric)
RandomMcSomethin
fallingleaves-1.5.0+1.16.5.jar
Fast Furnace for Fabric
tfarecnim
fastfurnace-2.4.jar
Flight Rings [FABRIC]
tired9494
[1.16.4] Flight Rings 1.4.2.jar
FlytreLib
Flytre7
flytre_lib-0.2.8.jar
FPS - Display
Gray_ray
fpsdisplay-1.16.4-v1.3.0.jar
FTB Ultimine (Fabric)
LatvianModder
ftb-ultimine-1605.2.0-build.26-fabric.jar
GameInfo
ifcifc
GameInfo-mod-2.1.0b 1.16.5.jar
GeckoLib [FABRIC]
ThanosGecko
geckolib-fabric-1.16.5-3.0.29.jar
Give Me Hats! [FABRIC]
Acrogenous
give-me-hats-1.16-1.5.jar
Go Fish
Draylar1
go-fish-1.2.1-beta-1.16.4.jar
Golden Steak
chronos_sacaria
goldensteak-1.0.2.jar
Golems Galore
ffrannny
golemsgalore-0.2.1+mc.1.16.5.jar
Gravestones
geometrically_
gravestones-v1.9.jar
Greater Eye of Ender [FABRIC]
kwpugh
GreaterEye-Fabric_1.16.5-1.1.5.jar
Grind Enchantments
mschae23
grind-enchantments-1.1.3+1.16.3.jar
HerdsPanic
Globox_Z
herdspanic-1.0.1.jar
Hexxit Gear (Fabric)
UltrusBot
hexxitgear-1.1.2.jar
Hwyla
TehNut
Hwyla-fabric-1.16.2-1.9.23-79.jar
Hwyla Addon Horse Info
Pancham138
hwyla-addon-horseinfo-0.2.2-1.16.1.jar
Improved Stations (Fabric)
shedaniel
improved-stations-2.0.3.jar
Inventory Sorting
Kyrptonaught
InventorySorter-1.7.8-1.16.jar
Iron Jetpacks Fabric
shedaniel
iron-jetpacks-0.3.1.jar
Item Scroller
masady
itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029.jar
Jumploader
comp500
jumploader-2.1.3.jar
Lapis Reserve
sfort__
lapisreserve-1.0.6.jar
LavaSponge [Fabric]
EndermanWhoSearchTheBeast
lavasponge-1.0.1.jar
LibCapableData (LibCD)
LemmaEOF
libcd-3.0.3+1.16.3.jar
Magic Mirror [FABRIC]
tired9494
[1.16.3+] Magic Mirror 1.2.jar
Magnet for Fabric
Motschen
FabricMagnet-1.16.1-1.0.0.jar
MaLiLib
masady
malilib-fabric-1.16.4-0.10.0-dev.21+arne.5.jar
Materialisation
shedaniel
materialisation-3.0.3.jar
MinecraftCapes Mod
james090500
MinecraftCapes Forge 1.16.5-v10.jar
Mining Dimensions [FABRIC]
kwpugh
MiningDimensions_Fabric_1.16.5-1.0.4.jar
Mo' Structures
ffrannny
mostructures-1.1.1+mc.1.16.5.jar
Mob Origins
UltrusBot
moborigins-1.3.1.jar
Mobs Attempt Parkour
Barribob
mobs-attempt-parkour-0.2.2-1.16.5.jar
Mod Menu
ProspectorDev
modmenu-1.16.9.jar
Monsters in the Closet
Minenash
monsters-in-the-closet-1.0.0+1.16.jar
More Death Messages [FABRIC]
jamalam360
moremessages-1.2.0.jar
More Gems [FABRIC]
kwpugh
MoreGems-Fabric_1.16.5-1.1.22.jar
Mythic Metals
Noaaan
mythicmetals-0.9.9.jar
Not Enough Crashes (Fabric)
NatanFudge
notenoughcrashes-3.1.8-fabric.jar
Not Enough Milk
suitedllama
not-enough-milk-1.1.0.jar
Notes Fabric
reeve567
notes-1.16.2-1.0.4.jar
Oh The Biomes You'll Go [FABRIC]
AOCAWOL
byg-1.1.7.jar
OPChanter
SaFiKiK
opchanter-1.16.4-2.0.0.jar
OresPlus [FABRIC]
makubas
Ores-Plus-1.0.0.jar
Origins
Apace100
Origins-1.16.5-0.7.0.jar
Origins: Classes
Apace100
Origins-Classes-1.16.5-1.1.1.jar
Origins: Umbrellas
Fusion_Flux
originsumbrellas-1.1.0.jar
Pehkui
Virtuoel
Pehkui-1.9.0+21w10a.jar
Pet Owner
potatoboy99999
PetOwner-1.7.1-1.16.2+.jar
Plant In A Jar
cool_mineman
plantinajar-1.8.1.jar
Pling
haykam
pling-1.3.0.jar
Polymorph (Fabric)
TheIllusiveC4
polymorph-fabric-0.0.10-1.16.5.jar
Portal Tags
cool_mineman
portaltags-2.1.0.jar
Quartz Elevator
atonkish
quartz-elevator-1.2.1-1.16.5.jar
Ring of the Enderchest [FABRIC]
kwpugh
RingOfEnderchest-Fabric-1.16.5-1.0.27.jar
Ring of the Miner [FABRIC]
kwpugh
RingOfMiner-Fabric_1.16.5-1.1.2.jar
Roughly Enough Items Fabric (REI)
shedaniel
RoughlyEnoughItems-5.11.188.jar
Roughly Enough Resources
theorbagain
rer-2.1.3.jar
Ruined Equipment
Pepperoni__Jabroni__
ruined-equipment-1.2.4.jar
Sandwichable
FoundationGames
sandwichable-1.2-beta5--1.16.5.jar
Save My Stronghold! (Fabric)
YUNGNICKYOUNG
SaveMyStronghold-Fabric-1.16.4-1.0.jar
Silky Spawners
traverse_joe
Silky-Spawners-2.1.0+build.2-1.16.jar
Sit (Fabric)
bl4ckscor3
sit-1.16.2-9.jar
Slime Sling
Flytre7
SlimeSling-1.0.0.jar
Snad - Back to the past
lazynessmind
snad-1.0.5-1.16.5.jar
Spellbound Enchantments
TigerOfTroy
spellbound-1.2.1.jar
Staff of Building
Draylar1
staffofbuilding-1.2.5-1.16.5.jar
Straw Dummy
GabrielHOlv
strawdummy-1.4.0.jar
The Aether Reborn
ImmortalDevs
aether-1.16.5-1.0.2.jar
The Bumblezone (Fabric)
telepathicgrunt
the_bumblezone_fabric-1.16.5-2.3.0.jar
The Warp Mod - Fabric
DrewChase
warpmod-fabric-1.16.5-0.0.3.jar
ThrowableTorch (Fabric)
DaniK1ngRD
throwabletorch-1.2.jar
Timber Mod by MYCF [FABRIC]
TheJoitwo
timber-1.0.1.jar
Time in a Bottle (Fabric)
alkyaLy
time-in-a-bottle-1.2-mc1.16.4-fabric.jar
Trinkets (Fabric)
EmilyPloszaj
trinkets-2.6.7.jar
True Secret Rooms
LudoCrypt
true-secret-rooms-1.1.3.jar
Vanilla Hammers
Draylar1
vanilla-hammers-3.0.2-1.16.5.jar
Villager Names (Fabric)
YumatanGames
villagernames-1.16.4-1.6.0.jar
VM Computers
delta2force
mcvmcomputers-1.4.15.jar
VoxelMap
MamiyaOtaru
fabricmod_VoxelMap-1.10.15_for_1.16.5.jar
Where Is It
JackFred2
whereisit-1.16.5-1.11.7.jar
Winged
AdrianTodt
winged-1.16.2-1.4.1.jar
Wolves With Armor
Draylar1
wolves-with-armor-1.5.2-1.16.2.jar
Wooden Hoppers
haykam
woodenhoppers-1.0.0.jar
XP Storage
sfinc
xp_storage-1.4+1.16.5.jar
YUNG's API (Fabric)
YUNGNICKYOUNG
YungsApi-1.16.5-Fabric-2.jar
YUNG's Better Caves (Fabric)
YUNGNICKYOUNG
BetterCaves-Fabric-1.16.5-1.1.jar
YUNG's Better Mineshafts (Fabric)
YUNGNICKYOUNG
BetterMineshafts-Fabric-1.16.4-1.0.1.jar

**Comment by OroArmor** [comment]
Give logs. I'm not going to test all of those and find the issue

**Comment by reasonableuser** [comment]
the thing is it didn't show a log just that there was an unexpected crash or something like that

**Comment by OroArmor** [comment]
https://fabricmc.net/wiki/player:tutorials:logs_ml:windows
https://fabricmc.net/wiki/player:tutorials:logs_ml:mac
