### ISSUE TITLE
[Compatibility conflict] Add compatibility for Origins

### ISSUE THREAD

**Issue by Disxconected** [OroArmor/Netherite-Plus-Mod#106]
**What is the mod and for which platform is it for**
Origins

**What feature(s) is in conflict**
lava vision 

Netherite plus conflicts rendering the lava vision from Origins dysfunctional 
![2021-04-16_13 45 16](https://user-images.githubusercontent.com/10158133/115063946-4396e400-9eba-11eb-91a7-a7963b154e47.png)
first image without netherite plus
![2021-04-16_13 49 12](https://user-images.githubusercontent.com/10158133/115064293-c455e000-9eba-11eb-8215-d8fa19e64a5f.png)
second image same perspective with netherite plus

**Comment by OroArmor** [comment]
Thanks, ill work on this later!
