### ISSUE TITLE
[Fabric | Forge] - Bug/Issue Config problems

### ISSUE THREAD

**Issue by DexTGS** [OroArmor/Netherite-Plus-Mod#107]
How do I config the mod? It says to restart the game but that doesn't work (I use Mr. Crayfish's "Configured" for config)

**Comment by OroArmor** [comment]
Edit the json file. I don't think configured would do anything

**Comment by DexTGS** [comment]
Ill look into it, thanks

**Comment by MrCrayfish** [comment]
Configured only works if the mod uses Forge's config system, however this mod uses a custom system.

**Comment by OroArmor** [comment]
Resolved with Crayfish's reply. Use cloth config for forge and the latest version of netherite Plus for a config screen.
