### ISSUE TITLE
[Fabric | Forge] - Bug/Issue

### ISSUE THREAD

**Issue by ToddlerConCo** [OroArmor/Netherite-Plus-Mod#108]
my friend and I recently started a server hosted on his pc using Fabric and it was going well, working out the kinks, and so we get most of the mods to work and no major errors in command prompt. but when we try to load into the server we both get a connection lost error saying "Registry remapping failed: Received ID map for minecraft:mob_effect contains IDs unknown to the receiver! - netherite_plus:lava_vision" so we get that and we dont know what is going on. it may be a conflict between mods but i do not know what mods would be conflicting.

(the error)
![image](https://user-images.githubusercontent.com/76507192/115134517-0cb1f280-9fce-11eb-9ae4-bfe5bf1ca66d.png)

we thought it would work normally but it didnt, we both on our clients and on the server side have the mods.

**Comment by OroArmor** [comment]
Could you provide game logs?

**Comment by OroArmor** [comment]
Also what version of the mod do you have?

**Comment by ToddlerConCo** [comment]
alright, my bad, i was watching my friends stream on discord helping him and he didnt have the mod installed. i didnt try to join with the mod
