### ISSUE TITLE
Not Appropriate Advancement Name

### ISSUE THREAD

**Issue by TerabyteTB** [OroArmor/Netherite-Plus-Mod#109]
I just looked at the README and I decided that something was very wrong: getting a fake netherite block gives you the advancement "Made In China". I just think this is kind of offensive to some people and I hope it could be fixed.

**Comment by OroArmor** [comment]
OMG i thought i changed that a long time ago. my apologies. i will fix it

**Comment by OroArmor** [comment]
Ok i fixed it thank you for pointing that out. I am very sorry
