### ISSUE TITLE
Fix compatibility for Quick Shulker

### ISSUE THREAD

**Issue by srnyx** [OroArmor/Netherite-Plus-Mod#114]
**What is the mod and for which platform is it for**
Quick Shulker, Fabric

**What feature(s) is in conflict**
Server crashes on startup: https://paste.srnyx.xyz/ovubicavox.sql

**Additional info**
Only happens with v1.4.4 of Netherite Plus Mod

**Comment by OroArmor** [comment]
I need to update my version of quick shulker for this. Thanks for the report
