### ISSUE TITLE
[Fabric] - Bug/Issue

### ISSUE THREAD

**Issue by mariokirby1703** [OroArmor/Netherite-Plus-Mod#116]
**Describe the issue**
I just downloaded the newest version of NetheritePlus (1.4.4. for Fabric) because it said I needed the latest one. Upon starting the game it crashed immediately. I'm using Fabric 0.11.3 for 1.16.5. And I was using NetheritePlus in my own private Modpack, which has ~130 more mods.

[crash-2021-05-21_21.44.19-client.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/6524813/crash-2021-05-21_21.44.19-client.txt)

**To Reproduce**
Maybe adding the same mods as me, maybe there are some compatibility issues...

**Expected behavior**
The game to start like normal.

**Screenshots**
![11111111111111mods](https://user-images.githubusercontent.com/60894103/119191709-4d92a080-ba7f-11eb-9192-f6fcb91ee3e5.PNG)

Thanks for the help!
-mariokirby1703

**Comment by OroArmor** [comment]
try without optifine
