### ISSUE TITLE
[Fabric] - Bug/Issue

### ISSUE THREAD

**Issue by FireDreamHy** [OroArmor/Netherite-Plus-Mod#117]
Can't Open with this mod
My Tlauncher can't open.

To Reproduce
Put the same mod i think

Expected behavior
I just can open Tlauncher 

Screenshots

![image](https://user-images.githubusercontent.com/84969837/119976332-a1d9db00-bfbf-11eb-84d6-711b0032fcef.png)

![image](https://user-images.githubusercontent.com/84969837/119976704-2cbad580-bfc0-11eb-8088-cda66d0f6f8a.png)

Thanks -FireDreamHy

**Comment by OroArmor** [comment]
Issue is simple, you have the forge version

**Comment by FireDreamHy** [comment]
thanks
