### ISSUE TITLE
What's with the gradle build errors?

### ISSUE THREAD

**Issue by TerabyteTB** [OroArmor/Netherite-Plus-Mod#118]
I looked at the commit and clicked on the red X and looked at the log. Something seems to be missing.

**Comment by OroArmor** [comment]
Don't know, what does it say is missing?

**Comment by TerabyteTB** [comment]
Could not find com.oroarmor:oro-config-forge:3.1.0.

**Comment by OroArmor** [comment]
Ah, you might want to fetch the latest commit. That was a custom version of one of my libraries that i was testing with. They should all be reverted to `3.0.0` now

**Comment by TerabyteTB** [comment]
I just looked at it. And there's no latest commit thing.
