### ISSUE TITLE
Netherite shears [Durability config]

### ISSUE THREAD

**Issue by Gomez96** [OroArmor/Netherite-Plus-Mod#125]
**Describe the feature you'd like**
I’ve noticed custom durability is missing for **netherite shears**. An option like this would be nice.

**Describe how this feature adheres to the vanilla feel**
It wouldn't change the game much. Just one option to make netherite shears even more useful to get and be more fun.

**Comment by OroArmor** [comment]
Ah I forgot to uncomment it thanks for letting me know
