### ISSUE TITLE
Game crashes right before reaching the main menu when used with Configured

### ISSUE THREAD

**Issue by dragon-evol** [OroArmor/Netherite-Plus-Mod#129]
When using Netherite Plus with Configured, the game crashes right before reaching the main menu.
Both mods I used were the latest release version for Minecraft 1.16.
I don't know which side the problem is on... but I'll post the crash report here.
I'm using a large mod pack so I don't know if this is caused by other mods? or Optifine?

[crash-2021-07-06_18.48.39-fml.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/6773985/crash-2021-07-06_18.48.39-fml.txt)

**Comment by OroArmor** [comment]
You need cloth config to open the config screen. I will add protections to make sure it doesn't crash the game in the next update

**Comment by dragon-evol** [comment]
Got it. Thanks for the reply!
