### ISSUE TITLE
Add compatibility for Gilded Netherite

### ISSUE THREAD

**Issue by TinyBoxer86** [OroArmor/Netherite-Plus-Mod#131]
The mod is Gilded Netherite, created by Azriel_Taylor.
When I have both of these mods installed, I get a crash on startup. I don't have this issue when only one of the two mods is installed, so I assume that it's a compatibility issue. I think that these two mods would go together really nicely, so compatibility would be awesome if at all possible! 

Thank you for your time and hard work on the mod so far, have a great day :)

**Comment by OroArmor** [comment]
could you provide logs
telling me there is an issue isn't very helpful

**Comment by OroArmor** [comment]
also I have worked for compatibility with this mod, so I don't know why it would break

**Comment by TinyBoxer86** [comment]
Man, I'm sorry, I hadn't realized that you already got compatibility working. It must be something else funky happening on my end; I double-checked with the most recent versions by themselves after seeing your comment and they worked just fine. Thank you anyway for your quick response, I really appreciate it! :)
