### ISSUE TITLE
[Forge] - Netherite Shulker Box Nesting

### ISSUE THREAD

**Issue by Violet-Scarelli** [OroArmor/Netherite-Plus-Mod#133]
**Describe the bug**
Netherite Shulker Boxes can be recursively stacked inside each other. This can and will eventually cause a game crash by hitting the NBT tag depth limit. 
**To Reproduce**
Put a netherite shulker box inside another netherite shulker box.

**Expected behavior**
You're able to put a netherite shulker box inside another netherite shulker box. This is not possible with normal shulkers.

**Comment by OroArmor** [comment]
What other mods do you have installed?
