### ISSUE TITLE
[Forge] - Bug/Issue - log spam

### ISSUE THREAD

**Issue by Awesomespore** [OroArmor/Netherite-Plus-Mod#136]
**Describe the bug**
I was looking through the logs since the game was lagging while in the nether (I don't think that's because of this mod), and I noticed that this line appears many times:
[Render thread/INFO] [STDOUT/]: [com.oroarmor.netherite_plus.client.NetheritePlusClientMod:lambda$init$1:45]: received

 

_I also saw this and thought it was funny
[Render thread/WARN] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Unable to play empty soundEvent: minecraft:music.nether.warped_forest_

**To Reproduce**
Unsure, just play in a world and check the logs I suppose?

**Expected behavior**
No log spam

**Comment by OroArmor** [comment]
thanks, ill look into this
