### ISSUE TITLE
[Fabric] - Netherite Elytra does not hide cape (Similar to #44)

### ISSUE THREAD

**Issue by Roadhog360** [OroArmor/Netherite-Plus-Mod#143]
**Describe the bug**
When wearing a Netherite Elytra, it applies the cape texture as expected, but does not hide the cape unlike the vanilla elytra

**To Reproduce**
Have a cape and wear a Netherite elytra. Compared to the normal elytra, cape is not hidden.

**Expected behavior**
The cape should be hidden.

**Screenshots**
![2022-07-30_21 38 35](https://user-images.githubusercontent.com/11903511/182007406-c84dfb9b-2df2-40d5-a62a-3d27664c8cc7.png)
![2022-07-30_21 38 46](https://user-images.githubusercontent.com/11903511/182007411-3ecaf31a-6564-4305-9094-bca30abba0b4.png)

This is similar to #44. However it was closed as resolved and did not specify if it was Fabric or Forge, so I am opening a new issue under the assumption this isn't a duplicate, and is just related instead.

Running on 1.4.5-1.16.5 using Fabric 0.14.8.

**Comment by Roadhog360** [comment]
Will the fix be backported to 1.16, or is the mod permanently moving to 1.19?

**Comment by OroArmor** [comment]
it will not be back ported. the mod was unable to compile and needed a rewrite.
