### ISSUE TITLE
Netherite Chests

### ISSUE THREAD

**Issue by 1198159** [OroArmor/Netherite-Plus-Mod#18]

**Comment by OroArmor** [comment]
what would these do? i think this is going a bit too far with netherite stuff

**Comment by rxay579** [comment]
More storage and fire/blast proof?  If you're trying to stay unique, it's kinda already covered by a netherite chest in Expanded Storage (https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric).
It has something like 25 rows of slots.

**Comment by OroArmor** [comment]
maybe! im trying to stay with the vanilla feeling of the game, and i feel like that is kinda pushing it a little too far.

**Comment by OroArmor** [comment]
Doesnt fit in with the rest of the mod
