### ISSUE TITLE
NP v1.5.0 - No Flight in Chest Slot, No Armor in Trinkets Cape Slot

### ISSUE THREAD

**Issue by rxay579** [OroArmor/Netherite-Plus-Mod#22]
Armor, but not flight in chest slot (yes, I know it's not supposed to go there ;)
![2020-08-01_14 47 26](https://user-images.githubusercontent.com/67221030/89109409-7c635b80-d406-11ea-9015-67369c95c2de.png)

Flight, but no armor in Trinkets "cape" slot.
![2020-08-01_14 47 37](https://user-images.githubusercontent.com/67221030/89109422-9d2bb100-d406-11ea-8f3c-2d3119f97ece.png)

Tested with NP v1.5.0, MC v1.16.1, Trinkets v2.6.3, Fabric 0.16.2, (plus many more).
Confirmed separately with clean instance with only NP, Trinkets, Fabric, and Malilib.

**Comment by OroArmor** [comment]
this is probably due to how minecraft calculates armor. i can probably fix this with a mixin in the next patch. thanks for letting me know
