### ISSUE TITLE
NP v1.6.1 - Netherite Anvil Issues

### ISSUE THREAD

**Issue by rxay579** [OroArmor/Netherite-Plus-Mod#23]
Attempting to rename an item (nametag, tool, etc) in a Netherite Anvil doesn't seem to work in Creative or Survival.
As you pull an item out, if resets it's position to the anvil's leftmost slot, takes the level, and the item isn't renamed.  This can be repeated until the player has no levels and renaming is not available.
Changes to XP afterwards (gain or loss) has the previously lost levels reappear on the XP bar.
Attempting to rename a tool while combining it with an enchantment add the enchantment, but does not rename the item.
Logs do not show abnormal behaviour.
The vanilla anvil appears to operate normally.

A falling Netherite Anvil that takes damage from the fall immediately breaks/disappears.
Not sure if this should be a separate issue.

**Comment by Lightone** [comment]
Other bug. dont have any sound when you enchant the items

**Comment by OroArmor** [comment]
Fixed! thanks for letting me know
