### ISSUE TITLE
NP v1.7.0 - Disabling Horse Armor in Config Gives Errors in Log

### ISSUE THREAD

**Issue by rxay579** [OroArmor/Netherite-Plus-Mod#24]
If you disable the Netherite horse armor in the config, the game logs errors when you enter a world.
Game / world appears to still function and Netherite horse armor no longer in items list, but not extensively tested.
Latest Log:
[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5048388/latest.log)

**Comment by OroArmor** [comment]
Ah thanks for letting me know, this should be relatively easy to fix, i just thought it wasnt going to be an issue. Its with the crafting recipes

**Comment by rxay579** [comment]
Might actually be affecting anything from this mod when disabled through the config.
Disabled everything (for science!) and the logged errors are quite a bit longer.
[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5048407/latest.log)

**Comment by OroArmor** [comment]
yeah definitely crafting

**Comment by OroArmor** [comment]
fixed with https://github.com/OroArmor/Netherite-Plus-Mod/commit/0b0282d8b4de1482a45c5b70ae481067475a4c06
