### ISSUE TITLE
NP v1.9.1 - Missing Netherite Trident Recipe

### ISSUE THREAD

**Issue by rxay579** [OroArmor/Netherite-Plus-Mod#27]
There doesn't appear to be a recipe (Smithing Table or otherwise) in NP v1.9.1 for the Netherite Trident.
Only tested in MC v1.16.1 (Fabric Loader 0.92, Fabric API v1.17.0).

**Comment by OroArmor** [comment]
Yes. I noticed this and it's already fixed for the next update.
