### ISSUE TITLE
NP v1.0.0 - MC 1.16.1 Backport, Pretty Please?

### ISSUE THREAD

**Issue by rxay579** [OroArmor/Netherite-Plus-Mod#31]
Not a bug, just a request for NP v1.0.0 (+) on MC v1.16.1.
Still waiting on some biome mods to update to 1.16.2.

**Comment by OroArmor** [comment]
Alright, i was planning on doing this, but i also made a bunch of updates to the fabric api stuff, and thats not out for 1.16.1, so i dont think i can
