### ISSUE TITLE
Netherite shears (Ideas)

### ISSUE THREAD

**Issue by Gomez96** [OroArmor/Netherite-Plus-Mod#37]
Hi! I came up with these ideas, so netherite shears would make sense and be worth of adding into a new mod version.

1. **Collecting stationary end crystals without explosion**

- Collecting a dragon egg without teleporting instead of using piston

- There'll be a high % chance that we'll get more chorus flowers, when breaking just one with netherite shears

- A small % chance of getting 2 dragon eggs, when breaking just one with netherite shears

2.  **Can remove the upper shell of shulkers making them more vulnerable to damage** 

- Removing Iron Golem's nose

-  Removing Elder Guardian's and Guardian's spikes, so they can't deal damage anymore with spikes and will have less health

- Deleting Hoglin and Zoglin's tusks, so this mob will cause much less damage

- Cutting off the Piglin's, Piglin brute's and zombified piglin's tusks making the mob more vulnerable to damage

- Getting rid of Devastator's horns, so the mob will have weakened attacks and be more vulnerable to damage

- Acquiring Strider's strings without killing

3. **Removing Vex's wings, so it won't be able to fly**

- Deleting Witch's hat

- Breaking the melon block will give us 9 melon pieces like in Minecraft Bedrock Edition

- Can break chorus plants as fast as netherite axe

- Can destroy vines way faster than iron shears

- High % chance of getting more **vines, grass, lily pads, leaves, ferns, dead bushes, seagrass, sea pickles, flowers, crimson and warped fungus, mushrooms, crimson and warped roots, nether sprouts, weeping and twisting vines, sugar canes, kelps, bamboos, cactuses, mushrooms from mushroom blocks and corals**, when breaking just one with netherite shears

- High % chance of getting more wool from sheeps

- Cutting off the cow's horns

**Comment by OroArmor** [comment]
@Gomez96 Asking me in other issues about your idea is the _wrong_ way to do things. I have thought about it, but had other priorities to work on first. I will reevaluate, but don't ask in other issues

**Comment by OroArmor** [comment]
As well, most of your suggestions dont have a vanilla feeling, and that is the main goal of my mod.

**Comment by Gomez96** [comment]
> reevaluate

I thought you forgot this as I've seen you were answering newer posts and you didn't answer for this one before. I'll understand and accept your refusal after your reevaluating.

**Comment by milkev** [comment]
I would like to note that I think Netherite Shears could be good even with just a simple Durability increase over iron shears. when gathering large amount of leaves shears really dont last very long. (ex: when gathering leaves to make custom trees, plants, bushes, etc.)
especially if you combine it with something like veinminer the vanilla shears durability can be used up in just a handful of clicks... even with unbreaking 3.

**Comment by Gomez96** [comment]
> I would like to note that I think Netherite Shears could be good even with just a simple Durability increase over iron shears. when gathering large amount of leaves shears really dont last very long. (ex: when gathering leaves to make custom trees, plants, bushes, etc.)
> especially if you combine it with something like veinminer the vanilla shears durability can be used up in just a handful of clicks... even with unbreaking 3.

I sent this idea for other mod before, but everyone said they'd be useless, if they would have the same features as iron ones. That's why it wasn't approved and added.

**Comment by milkev** [comment]
i mean-
all the vanilla netherite stuff has the same features as diamond gear, with the exception of armour getting knockback resistance
the durability upgrade is really the only significant buff vanilla gear gets, and its more than worth it in my opinion. modded items dont need to have a billion different fancy uses

**Comment by Gomez96** [comment]
> i mean-
> all the vanilla netherite stuff has the same features as diamond gear, with the exception of armour getting knockback resistance
> the durability upgrade is really the only significant buff vanilla gear gets, and its more than worth it in my opinion. modded items dont need to have a billion different fancy uses

Alright then. I don't mind as long as it gets added anyway.
