### ISSUE TITLE
[Crash] Guilded netherite

### ISSUE THREAD

**Issue by SylisMC** [OroArmor/Netherite-Plus-Mod#38]
**[Startup crash]**
**GameVer :** 1.16.4
**Fabric: Version:** 0.6.1.51 (Latest)
**Mods** `gilded-netherite-fabric-1.5.2.jar` & `netherite-plus-mod-1.1.0-1.16.4` https://www.curseforge.com/minecraft/mc-mods/gilded-netherite-for-fabric?page=2
`gilded-netherite-fabric-1.5.2.jar` + NP latest = Crash
`gilded-netherite-fabric-1.5.1.jar` + NP latest = Crash
`gilded-netherite-fabric-1.5.0.jar` + NP latest = Crash
`gilded-netherite-fabric-1.4.0.jar` + NP latest = Crash
`netherite-plus-mod-1.0.0` + GN latest = Crash
`netherite-plus-mod-1.1.0-1.16.4` + GN latest = Crash
`netherite-plus-mod-beta-1.9.1` + GN latest = Crash
Crash log is for latest of both mods, with jumploader, modmenu, fabric api

**Comment by SylisMC** [comment]
[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5712907/latest.log)

**Comment by OroArmor** [comment]
Yes I am aware of this and working the the gilded netherite dev on a solution, but I have some personal responsibilities I have to finish first. Expect a solution by Saturday.

**Comment by SylisMC** [comment]
That was fast, no problem at all, didnt see anything in issues on it or on the curse disc
