### ISSUE TITLE
Netherite Shulker Boxes

### ISSUE THREAD

**Issue by Naritix** [OroArmor/Netherite-Plus-Mod#39]
Stand on top of a Netherite Shulker Box. It immediately crashes my game, in any world. That bug's caused me to lose a hardcore world that I've spent around a week on. Please, fix this. If you can or can't fix, please contact me telling me so: V2RAMail@gmail.com

**Comment by OroArmor** [comment]
Could you provide a game log? I'll work on it tonight and release a fix

**Comment by OroArmor** [comment]
I just tested this, and i could not reproduce this bug
is it possible that you are using an older version of the mod? (i think i remember this from a while ago)

**Comment by Naritix** [comment]
I've been using 1.1.0, as 1.2.0 wasn't out at the time. I'll update it, see if that changes anything.
