### ISSUE TITLE
Conflict with Trinkets

### ISSUE THREAD

**Issue by milkev** [OroArmor/Netherite-Plus-Mod#4]
There appears to be (to my knowledge reading the crash report) a crash on startup related to netherite plus & patchouli.
If this is a problem with patchouli you cant fix, i can post this on their issue page. If its not related to patchouli, my bad. either waythe game crashes on launch.

https://pastebin.com/8jiwDnzZ

**Comment by OroArmor** [comment]
It looks like the mod in issue is trinkets, which I saw someone else mention. I haven't had a chance to look into it fully

**Comment by milkev** [comment]
i dont have much experience with modding, but the fact that it adds armor might be a problem if its allowed to be put in the trinkets elytra slot. not sure how all that works tho.

**Comment by OroArmor** [comment]
hey im working on this right now, and it looks like it should be an easy fix!

**Comment by milkev** [comment]
awesome! i look forward to flying around with a netherite elytra

**Comment by OroArmor** [comment]
ill make a new release shortly
