### ISSUE TITLE
[Bug] Modmenu transparency

### ISSUE THREAD

**Issue by SylisMC** [OroArmor/Netherite-Plus-Mod#40]
Modmenu supports transparency (the current netherite plus mod is not transparent) 
![nptb](https://user-images.githubusercontent.com/19602662/102817006-f1770380-439c-11eb-8d3c-8ca5872a035c.PNG)
not sure if you care, but I happened to notice it was transparent on the website/curse page but not in modmenu

**Comment by OroArmor** [comment]
Fixed
