### ISSUE TITLE
Capes don't work correctly with netherite elytra

### ISSUE THREAD

**Issue by Readf0x** [OroArmor/Netherite-Plus-Mod#44]
The cape does not dissapear, nor does the elytra use the cape texture when using a cape. I know it's at the very least possible to do, since the [Winged](https://www.curseforge.com/minecraft/mc-mods/zephyr) mod does do this.
![ex. A](https://user-images.githubusercontent.com/57838054/104374854-17994a80-54e8-11eb-87e7-7029b725a405.png)
![ex. B](https://user-images.githubusercontent.com/57838054/104374861-1a943b00-54e8-11eb-968b-8222724b34e1.png)

**Comment by Readf0x** [comment]
NOTE: the winged mod doesn't use the elytra texture as far as I know, and personally, I don't care about the elytra texture being rendered, but that's your decision, especially since you're the developer, and I'm just some dude trying to play modded minecraft...

**Comment by OroArmor** [comment]
fixed in the next release
