### ISSUE TITLE
(Forge) Fishing crashes the game

### ISSUE THREAD

**Issue by CephalonSinisite** [OroArmor/Netherite-Plus-Mod#45]
Pulling the fishing rod's bobber back in the overworld and It landing in the nether causes the game to crash
[crash-2021-01-14_20.15.12-server.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/5816583/crash-2021-01-14_20.15.12-server.txt)
[crash-2021-01-14_20.18.26-server.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/5816584/crash-2021-01-14_20.18.26-server.txt)
[crash-2021-01-14_20.21.50-server.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/5816585/crash-2021-01-14_20.21.50-server.txt)
[2021-01-14-1.log.gz](https://github.com/OroArmor/Netherite-Plus-Mod/files/5816616/2021-01-14-1.log.gz)
[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5816617/latest.log)
[2021-01-14-2.log.gz](https://github.com/OroArmor/Netherite-Plus-Mod/files/5816613/2021-01-14-2.log.gz)

**Comment by OroArmor** [comment]
Wow I never would have thought to test this. I'll look into it. Thanks for finding it!

**Comment by CephalonSinisite** [comment]
Forgot to mention that the netherite fishing rod used was enchanted with LotS 3 and Lure 3 with Unbreaking 3 and Mending

**Comment by OroArmor** [comment]
ok ill release a new patch in a couple days or two to fix it

**Comment by OroArmor** [comment]
fixed with 1.3.2
