### ISSUE TITLE
[Fabric]  crash on startup

### ISSUE THREAD

**Issue by CasualGoats** [OroArmor/Netherite-Plus-Mod#46]
Starting the game in MultiMC and it crashes before ever starting up the client. Uninstalled all other mods and it still persists. 

Crash Log
https://pastebin.com/z63PEaM9

**Comment by OroArmor** [comment]
Weird. It seems that architectury isn't loading properly. Download the fabric version from curseforge to fix it for now. I'll look into why it's not loading automatically

**Comment by OroArmor** [comment]
fixed with the latest release
