### ISSUE TITLE
Changing the config crashes the game

### ISSUE THREAD

**Issue by zeton54** [OroArmor/Netherite-Plus-Mod#48]
Minecraft throws this if config was edited
![1](https://user-images.githubusercontent.com/48909637/104829111-de0e6980-5870-11eb-9928-f1e875469e59.jpg)

[My config file ](https://drive.google.com/file/d/19AmYUZ6DnXe-v1-MxN0r-hQ8WxqIf6st/)
[Crash report](https://drive.google.com/file/d/1QWSHhcr-Km6_U4Fcdd4kkg9w-3V08Vnt/)

**Comment by OroArmor** [comment]
fixed with the latest release
