### ISSUE TITLE
Bow and Crossbow

### ISSUE THREAD

**Issue by jahirtrap** [OroArmor/Netherite-Plus-Mod#50]
**Describe the bug**
- Forge - crossbow_damage_multiplier in config file don't work.
- You should check the netherite bow textures, just rename them to display correctly.

**Expected behavior**
Even if the damage multiplier of the crossbow changes, it continues to do the default damage, the other objects do work correctly.

**Comment by OroArmor** [comment]
Fixed in the latest release
