### ISSUE TITLE
[Forge 1.16.4 - 35.1.37] - (Crash) Error during mod loading - java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by StygianEmperor** [OroArmor/Netherite-Plus-Mod#51]
I suspect Netherite Plus just took the blame for something else going on, so apologies in advance if this report seems trite.

**Version**
`forge-1.16.4-35.1.37`
`architectury-1.3.81-forge`
`netherite-plus-mod-1.3.3-1.16.5-forge`

**Describe the bug**
Crash on starting Minecraft, _probably due to incompatibility with another mod:_
> Netherite Plus (netherite_plus) encountered an error during the complete event phase
> java.lang.NullPointerException: null

**To Reproduce**
1. Download 140 disparate mods over the course of a couple months, any two of which _could_ potentially be incompatible...
2. Launch Minecraft with the Forge loader
3. **Crash!**
4. Optional. Report to the author of the mod specified in the crash screen and possibly learn what a "Null Pointer" is after first hearing it referenced in Borderlands 3 like a year ago.

**Expected behavior**
"I expected Minecraft to launch without crashing" is probably a tired joke at this point, sorry.

**Screenshots**
I'll just upload the logs here:
[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5832779/latest.log)
[crash-2021-01-18_17.16.47-fml.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/5832780/crash-2021-01-18_17.16.47-fml.txt)

**Comment by OroArmor** [comment]
Not sure. Did you disable anything in the config?

**Comment by StygianEmperor** [comment]
I did: Elytra, Fake Blocks, and I added 1.0 to the damage additions of all three items.

```
{
  "enabled": {
    "shulker_boxes": true,
    "elytra": false,
    "shields": true,
    "bows_and_crossbows": true,
    "fishing_rod": true,
    "horse_armor": true,
    "fake_netherite_blocks": false,
    "anvils": true,
    "config_debug_print": false,
    "trident": true,
    "beacon": true
  },
  "durabilities": {
    "elytra": 864,
    "fishing_rod": 128,
    "shield": 672,
    "bow": 768,
    "crossbow": 652,
    "trident": 500
  },
  "damage": {
    "bow_damage_addition": 1.0,
    "bow_damage_multiplier": 1.0,
    "crossbow_damage_addition": 1.0,
    "crossbow_damage_multiplier": 1.0,
    "trident_damage_addition": 1.0,
    "trident_damage_multiplier": 1.0
  },
  "anvil": {
    "xp_reduction": 0.5
  },
  "graphics": {
    "lava_vision_distance": 0.25
  }
}
```

**Comment by OroArmor** [comment]
Alright I think i know what it is. Should be an easy fix.

**Comment by StygianEmperor** [comment]
Damn, gotta respect that response time.

**Comment by OroArmor** [comment]
Lol. Expect a fixed version out in 6ish hours. It's cause I have no life lmao

**Comment by OroArmor** [comment]
Alright, fixed with the latest version!
