### ISSUE TITLE
Doesn't work Minecraft 1.16.5 [Fabric | Forge] - Bug/Issue

### ISSUE THREAD

**Issue by lexatwist** [OroArmor/Netherite-Plus-Mod#52]
When trying to launch MC with the Netherite Plus mod, no items show up in the creative inventory nor can I craft anything. I have FabricAPI 1.16.5 aswell. I'm not sure what could be causing this. Thanks!

**Comment by OroArmor** [comment]
could you provide a log?

**Comment by OroArmor** [comment]
and your config file? if you could run with the `enable_debug_print` set to true and provide that log

**Comment by lexatwist** [comment]
> could you provide a log?

not sure what i can provide other than some screenshots, what else can I do?

(note: i'm using the philza texture pack, but that shouldnt affect anything)

![smithin table](https://user-images.githubusercontent.com/77769991/105286933-3ac99700-5b85-11eb-9d26-f1b5e2bbe90b.png)
![netherite menu](https://user-images.githubusercontent.com/77769991/105286934-3ac99700-5b85-11eb-9a29-2987fa7ae622.png)

**Comment by OroArmor** [comment]
i cant help you unless i have logs. there should be a folder in your Minecraft installation called logs. provide me with the latest one

**Comment by lexatwist** [comment]
[2021-01-21-7.log.gz](https://github.com/OroArmor/Netherite-Plus-Mod/files/5847246/2021-01-21-7.log.gz)

**Comment by OroArmor** [comment]
ah you downloaded the forge version of the mod

**Comment by lexatwist** [comment]
can you provide the Fabric version so I don't mess it up again?

**Comment by OroArmor** [comment]
there are two downloads
just download the one with fabric in the name
