### ISSUE TITLE
Problem with loading game "shulker problem"

### ISSUE THREAD

**Issue by LowGr1m** [OroArmor/Netherite-Plus-Mod#54]
Hi, i using java minecraft 1.16.4 with forge 35.1.28 my other mods which get to effect shulkers are: shulkersception-1.16-1.0 and Shulker-Drops-Two-Mod-1.16.4. 

Issue got identified on mod version 1.3.0 forge

Sending logs to deeper identify my actual problem i hope it will help you :-)

[2021-01-26-6.log.gz](https://github.com/OroArmor/Netherite-Plus-Mod/files/5873767/2021-01-26-6.log.gz)

**Comment by OroArmor** [comment]
Update to 1.3.8 and install architectury. That should fix your issue. I don't know abiu5 compatibility with the other mods, so if their features aren't working,we can keep this issue open for me to add compatibility.

**Comment by LowGr1m** [comment]
Thanks a lot for helping me! :-) ... Works amazingly :-) ... and mod shulkersception-1.16-1.0 is compatabile with your mod as well :-) ... the other shulker mod is just for improve drop rates. Thumbs up to you! :-) I think it was just dumb from me to not get your lastest version of mod.

**Comment by OroArmor** [comment]
Alright awesome!
