### ISSUE TITLE
Adding banner patterns to Netherite shields.

### ISSUE THREAD

**Issue by RedstoneParadox** [OroArmor/Netherite-Plus-Mod#55]
**Describe the feature you'd like**
Vanilla shields can have banner patterns added, so it only makes sense that Netherite shields could have banner patterns as well.

**Describe how this feature adheres to the vanilla feel**
It's literally a vanilla feature.

**Comment by OroArmor** [comment]
wait is it not working?

**Comment by RedstoneParadox** [comment]
Nope, but I thought it was an oversight and not a bug.

**Comment by OroArmor** [comment]
ill check it out

**Comment by OroArmor** [comment]
ok this is fixed in the next version
