### ISSUE TITLE
Minecraft crashes when trying to start with the mod

### ISSUE THREAD

**Issue by QuoteXV** [OroArmor/Netherite-Plus-Mod#56]
When launching minecraft with the netherite plus mod it crashes and gives this message
![netherite plus mod](https://user-images.githubusercontent.com/78131653/106091509-74e4ec80-60e1-11eb-9b13-783672f453e8.png)

**Comment by OroArmor** [comment]
could you provide a game log?
I cant debug with just this error

**Comment by QuoteXV** [comment]
Heres the crash report

[crash-2021-01-27_20.44.41-client.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/5885046/crash-2021-01-27_20.44.41-client.txt)

And here's the latest log

[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5885050/latest.log)

**Comment by OroArmor** [comment]
update your fabric api. its an old version

**Comment by OroArmor** [comment]
this wont crash in future versions

**Comment by QuoteXV** [comment]
That worked! Thanks for your help!
