### ISSUE TITLE
Netherite bow, crossbow and fishing rod texture issues

### ISSUE THREAD

**Issue by abdmoh123** [OroArmor/Netherite-Plus-Mod#58]
When aiming the bow, the texture changes to the default bow texture without any arrows loaded.
When loading the crossbow with arrows or fireworks (and after it is loaded), the texture changes to the default wooden one.
Finally, when using the new fishing rod, the texture changes to the wooden one (with the tackle still attached when it shouldn't be).

**Comment by OroArmor** [comment]
Could you provide some screenshots?

**Comment by abdmoh123** [comment]
Here:

![2021-02-06_20 08 40](https://user-images.githubusercontent.com/52327899/107128650-41f7e100-68b7-11eb-9397-28a4fe2c5157.png)
![2021-02-06_20 07 58](https://user-images.githubusercontent.com/52327899/107128652-44f2d180-68b7-11eb-80a4-30949aecc6b9.png)
![2021-02-06_20 08 06](https://user-images.githubusercontent.com/52327899/107128654-47edc200-68b7-11eb-87d6-04219c547cfc.png)
![2021-02-06_20 08 09](https://user-images.githubusercontent.com/52327899/107128656-4a501c00-68b7-11eb-86f4-d42f640f5607.png)
![2021-02-06_20 08 20](https://user-images.githubusercontent.com/52327899/107128657-4cb27600-68b7-11eb-9ba5-18d666c9aa94.png)

P.S. it seems fireworks don't show up when loading the crossbow.

**Comment by OroArmor** [comment]
weird... that doesnt happen in my test environment... what mod launcher are you using? fabric or forge?

**Comment by abdmoh123** [comment]
fabric

**Comment by abdmoh123** [comment]
Other than that bug the mod is fantastic

**Comment by mepland** [comment]
I am also not able to replicate when using the latest versions, with sodium and phosphor.

**Comment by OroArmor** [comment]
I wasnt able to replicate the issue, but i think i might have fixed it.
If you could try this, that would be helpful (just change the extension to `.jar` from `.zip`, github wont let me upload it otherwise)
[netherite-plus-mod-1.3.14-1.16.5-fabric.zip](https://github.com/OroArmor/Netherite-Plus-Mod/files/5937593/netherite-plus-mod-1.3.14-1.16.5-fabric.zip)

**Comment by OroArmor** [comment]
@abdmoh123 if you could test that, it would be great because i cant reproduce the issue

**Comment by abdmoh123** [comment]
I have good news and bad news:
Bad news is that the zip file didn't fix the problem.
The good news is that the problem was caused by a resource pack.

I am very sorry for wasting your time like this but thanks for the help!
