### ISSUE TITLE
Netherite shulker boxes can be put in normal or netherite shulker boxes

### ISSUE THREAD

**Issue by g5bb** [OroArmor/Netherite-Plus-Mod#61]
**Describe the bug**
Netherite shulker boxes can be put into normal or netherite shulker boxes

**To Reproduce**
Try putting a netherite shulker box into a normal or netherite shulker box

**Expected behavior**
For me to not be able to put the netherite shulker box in the normal or netherite shulker box

**Screenshots**
![Screenshot_6](https://user-images.githubusercontent.com/72352082/107712940-40a02d00-6c98-11eb-9e91-c4fb0d9df528.png)
![Screenshot_8](https://user-images.githubusercontent.com/72352082/107713576-8c070b00-6c99-11eb-8690-1d078165de4d.png)

**Comment by OroArmor** [comment]
Do you have other mods loaded?

**Comment by g5bb** [comment]
Yes.

**Comment by OroArmor** [comment]
which mods?

**Comment by g5bb** [comment]
AdventureZ
Sit
MoreBlocksMod
NookBuild

**Comment by OroArmor** [comment]
Alright this is fixed
