### ISSUE TITLE
[Fabric 1.16.5] Voxelmap and Netherite Plus (Crash)

### ISSUE THREAD

**Issue by Ohada214** [OroArmor/Netherite-Plus-Mod#62]
I wasn't sure, if I should have put this in **bug report** or **compatibility.**

**Describe the bug:**
I can't play the game at all, when I use Netherite Plus and Voxelmap at the same time even though I have the newest version of both these mods, newest fabric mod loader and fabric api. I checked the previous version of Netherite Plus and it works fine with Voxelmap. The problem occurs only in the newest version of Netherite Plus.

Launcher says: **The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error**

Here's the log: https://pastebin.com/1WUgRRhW

**To Reproduce:**
Put any version of Voxelmap mod inside the mods folder along with the newest version of Netherite Plus mod

**Expected behavior:**
Launcher should just load normally and show menu of the game

**Comment by OroArmor** [comment]
voxel map doesnt work with architectury. Their mod is also closed source, so i cannot help with this except say play without it sorry
