### ISSUE TITLE
Netherite shields cannot be disabled

### ISSUE THREAD

**Issue by g5bb** [OroArmor/Netherite-Plus-Mod#63]
**Describe the bug**
Netherite shields cannot be disabled by an axe, making them extremely overpowered

**To Reproduce**
1. Spawn an axe-wielding mob (vindicator or piglin brute.)
2. Go into a survival and hold out the netherite shield to them.

**Expected behavior**
For the netherite shield to be disabled.

**Comment by srnyx** [comment]
This may be intended

**Comment by OroArmor** [comment]
does it work with a vanilla shield?
i don't think it does cause the off hand isn't targeted from shift clicking

**Comment by srnyx** [comment]
> does it work with a vanilla shield?
> i don't think it does cause the off hand isn't targeted from shift clicking

_Wrong issue_
