### ISSUE TITLE
[Fabric 1.16.5] - Netherite fishing rod 

### ISSUE THREAD

**Issue by Ohada214** [OroArmor/Netherite-Plus-Mod#64]
**Describe the bug**
I cannot fish in the water at all. The fishing float of a netherite fishing rod automatically disappears once it hits the water. It's acting like I'm stopping it, when in fact I don't click anything to stop it.

**To Reproduce**
Use a netherite fishing rod to fish in the water in Overworld

**Expected behavior**
I expected netherite fishing rod to work for water as it works currently for lava.

**Proof**
Here's a video: https://www.youtube.com/watch?v=ddy8heMRBFQ

**Comment by OroArmor** [comment]
Should be fixed in the next release
