### ISSUE TITLE
New textures for vanilla items

### ISSUE THREAD

**Issue by Gomez96** [OroArmor/Netherite-Plus-Mod#65]
**Describe the feature you'd like**
What if a ''Netherite Hoe, Axe, Pickaxe, Shovel and Sword'' had the same textures as modded items like for example: ''Netherite bow'' or maybe some different textures like ''Netherite Trident and Netherite Elytra'' that differ more from vanilla ones with appearance? Same goes for ''Full set of netherite armor''

**Describe how this feature adheres to the vanilla feel**
Vanilla tools would look better, feel more enjoyable and unique in my opinion. 

**Additional context**
New textures of full netherite armor set could be inspired by this mod: https://www.curseforge.com/minecraft/mc-mods/gilded-netherite-for-fabric

**Comment by OroArmor** [comment]
Make a resource pack. I add to the vanilla feeling, but I don't modify it.
