### ISSUE TITLE
[Fabric] - Bug/Issue - Dedicated Server crash when opening a netherite shulker box

### ISSUE THREAD

**Issue by dandin87** [OroArmor/Netherite-Plus-Mod#66]
**Describe the bug**
All of Fabric 3 v2.6.5 NA/EU Servers, netherite-plus-mod-1.3.17-1.16.5-fabric
Dedicated Server crash when opening a netherite shulker box
Remapped Crash Log - https://paste.lucko.me/PyzPC1xikT

**To Reproduce**
Steps to reproduce the crash/bug
Open a netherite shulker box

**Expected behavior**
not crash

**Comment by OroArmor** [comment]
Looks like the quickshulker api has changed... ill make a fix soon

**Comment by kyrptonaught** [comment]
I apologize for this, I made this change and completely forget it was something others used. I'll fix it on my end

**Comment by kyrptonaught** [comment]
This has been fixed in quickshulker 1.1.14
