### ISSUE TITLE
[Fabric] Bug

### ISSUE THREAD

**Issue by WieldyXD** [OroArmor/Netherite-Plus-Mod#67]
![image](https://user-images.githubusercontent.com/79330291/108546096-8edcae00-72e0-11eb-91d9-d16ce7abbf81.png)
I cant upgrade items to netherite

**Comment by OroArmor** [comment]
Make sure you have downloaded the correct version for your mod loader, and not for the other. The easiest way to tell is if the file for the mod ends with the mod loader you are using. -fabric for Fabric, and -forge for Forge. If you lost your items permanently, the only way to get them back is with cheats, and I wont help with that process.

**Comment by WieldyXD** [comment]
I did

**Comment by OroArmor** [comment]
Do you have any other mods installed or any datapacks?

**Comment by OroArmor** [comment]
Closing with no reply in 3 months
