### ISSUE TITLE
Forge - crashes while loading up minecraft

### ISSUE THREAD

**Issue by sugar-dealer** [OroArmor/Netherite-Plus-Mod#68]
I have the latest 1.16.4 Netherite Plus mod with forge version 35.1.4 I have no other mods installed
![Screenshot_1](https://user-images.githubusercontent.com/79334223/108553161-4b724780-72c0-11eb-813d-6ae493ee4aa6.png)

**Comment by OroArmor** [comment]
i need game logs

**Comment by OroArmor** [comment]
no install architectury read the curseforge page
