### ISSUE TITLE
[Fabric] Missing a dependency on Cloth Config

### ISSUE THREAD

**Issue by coderbot16** [OroArmor/Netherite-Plus-Mod#69]
**Describe the bug**
There's an unclear crash with ModMenu when you run without Cloth Config installed.

**To Reproduce**
Download and run without Cloth Config

**Expected behavior**
Cloth Config should be specified as a dependency in the fabric.mod.json of either Netherite Plus or Oro Config, and probably be bundled as a JiJ mod too.

**Screenshots**
Not applicable

**Comment by OroArmor** [comment]
Alright, i need to work on my config library, so a fix for this will be out in maybe a week

**Comment by OroArmor** [comment]
Fixed with the next version
