### ISSUE TITLE
[Fabric] crash

### ISSUE THREAD

**Issue by twig-maker** [OroArmor/Netherite-Plus-Mod#70]
![Screenshot 2021-02-21 060720](https://user-images.githubusercontent.com/79402323/108623104-20e0d580-740b-11eb-958c-580d463ff982.png)

**Describe the bug**
it keeps crashing

**To Reproduce**
I just start the game and that happens

**Expected behavior**
I thought I would click play and just get in and play

**Screenshots**

**Comment by twig-maker** [comment]
[crash-2021-02-21_06.23.28-client.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/6017600/crash-2021-02-21_06.23.28-client.txt)

**Comment by twig-maker** [comment]
im also using 12 other mods

**Comment by OroArmor** [comment]
Architectury is incompatible with voxelmap. remove it and the game will run
