### ISSUE TITLE
Error when joining Server

### ISSUE THREAD

**Issue by lanewhitten** [OroArmor/Netherite-Plus-Mod#72]
Registry remapping failed: Received ID map for Minecraft:mob_effect contains IDs unknown to the receiver! - netherite_plus:lava_vision

**Comment by OroArmor** [comment]
What version do you and the server have?

**Comment by lanewhitten** [comment]
1.16.5 It works fine for my Friends but not for me. 1.3.17

**Comment by lanewhitten** [comment]
I changed nothing and it now works

**Comment by OroArmor** [comment]
Oop ok sounds good
