### ISSUE TITLE
[Fabric | Forge] - Bug/Issue

### ISSUE THREAD

**Issue by ninonook1** [OroArmor/Netherite-Plus-Mod#73]
**Describe the bug**
I am using fabric, the device is a mac book air version: Bigslur, your mod is not working. I am unable to find anything that your mod introduced. the wings, for example, couldn't find it on creative invo, nor trying to craft it myself.

**To Reproduce**
I have no idea, my best guess is the device I use which I have stated above or a dependency mod which was shown in relation (I have the architecture API up and running)

**Expected behavior**
it should for my knowledge show items you've implemented, and or be able to make them (tried using the smithing table)

**Comment by OroArmor** [comment]
did you download the forge version of the mod? make sure the version you have ends in `-fabric`
