### ISSUE TITLE
[Fabric] - Bug/Issue

### ISSUE THREAD

**Issue by UnhappyEnderman** [OroArmor/Netherite-Plus-Mod#77]
Basically the entire log when i try to load into a server with the mod installed(FABRIC)
Log: https://cdn.discordapp.com/attachments/816261459817267260/817508640549896222/image0.jpg

Any fix? Im using aternos and the mods i have installed are:
architectury-1.8.130-fabric.jar
autoconfig1u-3.3.1.jar
fabric-api-0.31.0+1.16.jar
FallingTree-Fabric-1.16.5-2.10.2.jar
lithium-fabric-mc1.16.5-0.6.4.jar
netherite-plus-mod-1.3.17-1.16.5-fabric.jar
Origins-1.16.5-0.5.2.jar

**Comment by OroArmor** [comment]
install the mods server and client side
this is not a bug
