### ISSUE TITLE
Netherite Plus versions above 1.3.12 Crashes My Game Before Startup On Fabric

### ISSUE THREAD

**Issue by PhonieZ** [OroArmor/Netherite-Plus-Mod#79]
I have no idea why this is, but I will link all the mods I have, I am using the latest fabric loader at the time,0.11.2 for 1.16.5
Mods I Have:https://drive.google.com/file/d/1gxipFEK4s6fSOQ2GWLVSTqFKbqi1ULke/view?usp=sharing
By the way these mods work with version 1.3.12 of netherite plus, as you can see because I included it, so remove it before testing with newer versions

**Comment by OroArmor** [comment]
Could you provide game logs? That will help me diagnose the issue easier

**Comment by OroArmor** [comment]
Closing with no reply in 3 months
