### ISSUE TITLE
May conflicts with Mobz

### ISSUE THREAD

**Issue by linzexin022** [OroArmor/Netherite-Plus-Mod#8]
Hi there, I tested this mod and found it may conflict with mod _Mobz_, here's the game log:

[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/4977201/latest.log)

Game Version: 1.16.1
Mod Version: netherite-plus-mod-trinkets-beta-1.1.2.jar

**Comment by OroArmor** [comment]
ah thank you, it shouldnt be hard for me to fix this, _i think_

**Comment by linzexin022** [comment]
Hi there, I tested this mod and it still conflicts with _Mobz_ mod.
**_Game_** Version: 1.16.1
**_Netherite Plus Mod_** Version: beta-1.7.0 for 1.16.1
**_Mobz Mod_** Version: 2.4.4 for 1.16.1

Here's the game log:
https://paste.ee/p/1FXdl

**Comment by OroArmor** [comment]
This is a conflict of api's, and i dont know if there will be an easy fix. I do know that there is an api in the works for shields, and that may fix it, but until then, id say these mods are incompatible
