### ISSUE TITLE
[Forge] - Netherite Elytra curios not rendering

### ISSUE THREAD

**Issue by alpharou** [OroArmor/Netherite-Plus-Mod#80]
curios 4.0.4.0
forge 36.0.43
netherite plus 1.4.0

![image](https://user-images.githubusercontent.com/8113318/110263409-de94c800-7fb6-11eb-9f35-fd32d8aac985.png)

Not visible
![image](https://user-images.githubusercontent.com/8113318/110263424-ebb1b700-7fb6-11eb-886e-b0b5b60a2384.png)

Equipped in normal chest slot
![image](https://user-images.githubusercontent.com/8113318/110263430-f4a28880-7fb6-11eb-9acc-59796ad9a306.png)

Beautifully visible (freaking love netherite elytra)
![image](https://user-images.githubusercontent.com/8113318/110263446-0552fe80-7fb7-11eb-8135-36270e323b16.png)

**Comment by OroArmor** [comment]
might be a curious thing, but i doubt it. ill double check their code to see why its not rendering, but i think i have a guess

**Comment by Gabo6480** [comment]
Also, it doesn't seem to give the armor stats to the player
