### ISSUE TITLE
[Fabric 1.16.5] - Fishing in lava

### ISSUE THREAD

**Issue by Ohada214** [OroArmor/Netherite-Plus-Mod#81]
**Describe the bug**
Not sure if that was intentional or it's a bug. The fishing float of a netherite fishing rod while fishing in lava falls down instead of floating on the surface of lava like it does in water. 

**To Reproduce**
Use a netherite fishing rod to fish in lava.

**Expected behavior**
It'd look better if the fishing float in lava worked the same as on water.

**Screenshots**
![1](https://user-images.githubusercontent.com/78999937/110331258-30713880-801f-11eb-84b0-ea336df96f89.jpg)
![2](https://user-images.githubusercontent.com/78999937/110331268-31a26580-801f-11eb-909e-8afe1223a305.jpg)

**Comment by OroArmor** [comment]
Minecrafts physics engine is horrible, it still fishes and works normally
