### ISSUE TITLE
[Forge] Netherite Trident Model Broken

### ISSUE THREAD

**Issue by sinksarecoolyes** [OroArmor/Netherite-Plus-Mod#82]
The model of the netherite trident is completely broken, it barely shows up in your hand and in f3 it goes through your legs and is small.
![2021-03-08_14 32 18](https://user-images.githubusercontent.com/80285424/110372356-31ed3180-801c-11eb-86bd-cc290e93b67f.png)
![2021-03-08_14 32 24](https://user-images.githubusercontent.com/80285424/110372372-34e82200-801c-11eb-8653-959fd2708933.png)

**Comment by sinksarecoolyes** [comment]
I forgot to add im on forge 36.0.42 and netherite plus 1.4.0

**Comment by choufchouf123** [comment]
I have the exact same problem

**Comment by OroArmor** [comment]
Forge breaks item rendering in a way that i don't understand why. It stays broken because forge breaks it
