### ISSUE TITLE
[Fabric] - Bug/Issue Failed to join server

### ISSUE THREAD

**Issue by Revenent666** [OroArmor/Netherite-Plus-Mod#83]
Registry remapping failed: Received ID map for Minecraft:block contains IDs unknown to the receiver! - netherite_plus:fake_netherite_block

I'm running a Fabric Server for 1.16.5 and I'm using Netherite Plus Mod 1.4.0 Fabric I've played it for a bit, while playing I disabled the fake netherite block because I knew none of my friends and I would never use it. Then closed the server to add the colytra mod turned the server back on and this message came up.

**Comment by Revenent666** [comment]
Yes I'm aware that colytra isnt fully compatible at the moment

**Comment by OroArmor** [comment]
is your config different than the one on the server?
this seems like its the issue, you accidentally disabled something server side and not client side.

It looks like colytra is causing it, but I'm not sure why. i would need to see client and server logs for when you try to join

**Comment by Revenent666** [comment]
okay

**Comment by Revenent666** [comment]
12.03 15:00:21 [Server] User Authenticator #1/INFO UUID of player Revenent666 is d840df70-3fca-461e-9ed2-07e2a787fe83
12.03 15:00:21 [Connect] User Revenent666, IP 117.20.66.14
12.03 15:00:21 [Server] Server thread/INFO Revenent666 joined the game
12.03 15:00:21 [Multicraft] Revenent666 ran command Message of the Day
12.03 15:00:21 [Server] Server thread/INFO Sending config to Revenent666 (d840df70-3fca-461e-9ed2-07e2a787fe83)
12.03 15:00:21 [Server] Server thread/INFO Sent markers data #-1 to player Revenent666
12.03 15:00:21 [Server] Server thread/INFO Sent custom biome data to player Revenent666
12.03 15:00:21 [Server] Server thread/INFO Sent custom biome data to player Revenent666
12.03 15:00:21 [Server] Server thread/INFO Sent custom biome data to player Revenent666
12.03 15:00:21 [Server] Server thread/INFO [STDOUT]: sending loot to Revenent666
12.03 15:00:22 [Disconnect] User Revenent666 has disconnected, reason: Disconnected
12.03 15:00:22 [Server] Server thread/INFO Revenent666 left the game

**Comment by Revenent666** [comment]
![Capture](https://user-images.githubusercontent.com/80468403/110890431-bea92f80-833b-11eb-8016-4f1693afe08d.JPG)

**Comment by OroArmor** [comment]
ah so yeah, you need to disable the item in your config as well, as there is currently no way for me to remove the block client side from the server, that should fix your issue

**Comment by Revenent666** [comment]
okay, Im using apex hosting, could you possibly give me a small walkthrough how to get to the mods config on the server side

**Comment by OroArmor** [comment]
dont know apex, but if you can upload/change files from some form of console, just do the same thing as you did with your config

**Comment by Revenent666** [comment]
found it and fixed it. thank you for your help. feel free to use this in case someone else comes up with this issue and is using apex. They need to go into:

FTP File Access
Login
Config
Find Netherite Plus and click on edit
Change it to their choosing of either true or false
Click save
Restart Server

**Comment by OroArmor** [comment]
Cool. You're welcome!
