### ISSUE TITLE
[Fabric | Forge] - Bug/Issue

### ISSUE THREAD

**Issue by Ensrick** [OroArmor/Netherite-Plus-Mod#84]
The server using Fabric 1.16.5 crashes with Netherite Plus. I've attached the log.
[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/6132589/latest.log)

**Comment by OroArmor** [comment]
yeah there is an issue with trinkets, downgrade to version 1.3.17 and wait for version 1.4.1

**Comment by OroArmor** [comment]
fixed in 1.4.1
