### ISSUE TITLE
[Fabric 1.16.5] - Netherite Beacons don't work in the nether due to the ceiling.

### ISSUE THREAD

**Issue by Coffe-e** [OroArmor/Netherite-Plus-Mod#85]
**Describe the bug**
Netherite Beacons, due to the Nether's ceiling, will not activate their effects unless open to the Nether's sky that's above the bedrock.

**To Reproduce**
Place a beacon in the nether with the required pedestal

**Expected behavior**
Netherite beacons to work in the nether, as they provide fire resistance and lava-vision.

**Comment by OroArmor** [comment]
*is there netherrack in the way*?
the netherite beacon goes through all blocks the beacon goes through, so you probably have a solid block in the way

**Comment by Coffe-e** [comment]
I'm a bit uninformed on how beacons work in the nether, but my assumption was that it'd go through things like netherrack, due to the fact that there was a ceiling of it. It seems to go through bedrock fine, so i'll just close this issue. Sorry about that!
