### ISSUE TITLE
Clash with voxelmap?

### ISSUE THREAD

**Issue by PaladinGFX** [OroArmor/Netherite-Plus-Mod#86]
I believe there is a slight clash with voxel map which causes the game to crash upon start up. I've quoted the crash log below to help diagnose the issue. I was able to test the clash by removing the voxel map from the mod folder and starting the game and vice versa. Not sure if there's anything that can be done but any fix would be greatly appreciated!

[crash-2021-03-15_17.40.50-client.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/6139391/crash-2021-03-15_17.40.50-client.txt)

**Comment by OroArmor** [comment]
Known issue with architectury. Cant fix it because voxelmap is closed source, so cant figure out the issue. use Xeros minimap as a replacement

**Comment by PaladinGFX** [comment]
Ahh bummer, no problem and thanks for the response!
