### ISSUE TITLE
config not working

### ISSUE THREAD

**Issue by ArcticLightning** [OroArmor/Netherite-Plus-Mod#87]
changing the values in the config/netherite_plus.json doesnt affect values in game.
for example, changing the elytra durabilty to 1000 does not change the netherite elytra's durabilty.
this is the same for all other values.
more info:
this is on a minecraft server.
i am using the most recent fabric version of the mod.

**Comment by OroArmor** [comment]
Yes, this is a known thing and is mentioned several times that a restart will be required for certain config values.
