### ISSUE TITLE
[Fabric] - Can't shift click shield

### ISSUE THREAD

**Issue by srnyx** [OroArmor/Netherite-Plus-Mod#89]
**Describe the bug**
You can't shift-click the netherite shield into the shield slot

**To Reproduce**
Use the mod

**Expected behavior**
The shield should be automatically put into the shield slot when shift-clicking it in the inventory

**Comment by OroArmor** [comment]
does it work with a vanilla shield?
i don't think it does cause the off hand isn't targeted from shift clicking

**Comment by srnyx** [comment]
> does it work with a vanilla shield?
> i don't think it does cause the off hand isn't targeted from shift clicking

Yep, it works

**Comment by OroArmor** [comment]
fixed for 1.4.1
