### ISSUE TITLE
[Fabric | Forge] - Bug/Issue Nehter portals not working properly

### ISSUE THREAD

**Issue by Lumen21** [OroArmor/Netherite-Plus-Mod#90]
**Describe the bug**
The portals transports you to other areas doesnt light up when built properly

**To Reproduce**
Enter a nether portal and it will transport to other area

**Expected behavior**
 Portals lighting up when ignited and transporting you to the proper area

**Screenshots**

**Comment by OroArmor** [comment]
I dont touch portals. Its another mod
