### ISSUE TITLE
[Fabric | Forge] - Bug/Issue 

### ISSUE THREAD

**Issue by Lumen21** [OroArmor/Netherite-Plus-Mod#91]
**Describe the bug**
Changing and/or erasing built structures on the nether

**To Reproduce**
Install the mod on a server enter a nether portal 

**Expected behavior**
Player built structures appearing on the nether side

**Screenshots**
![Screenshot (87)](https://user-images.githubusercontent.com/80564620/111403635-4d4ee100-869b-11eb-9728-61f0153dffa9.png)
![Screenshot (102)](https://user-images.githubusercontent.com/80564620/111403653-5344c200-869b-11eb-87ba-c67e5cce9aec.png)

**Comment by OroArmor** [comment]
Once again, netherite Plus doesn't touch any world Gen or structures. This is another mod or your jvm.

**Comment by Lumen21** [comment]
Thanks for the answer
