### ISSUE TITLE
[Forge] - Bug/Issue

### ISSUE THREAD

**Issue by krysx7003** [OroArmor/Netherite-Plus-Mod#92]
**Describe the bug**
I am using Forge 1.16.4.Trident when held appears too small and misplaced.

**To Reproduce**
Run forge 1.16.4 with mod instaled(pack with create,hwyla,doubleslabs,immersive-portals,jei,journey map and optifine. Ran it without other mods and the same thing happened)
**Expected behavior**
trident should look as large as normal trident and be alligned with hand
**Screenshots**
![2021-03-18_20 33 47](https://user-images.githubusercontent.com/80921437/111690510-9040be00-882d-11eb-9d2a-bc33edadf600.png)
![2021-03-18_20 33 57](https://user-images.githubusercontent.com/80921437/111690525-946cdb80-882d-11eb-931c-f663b3fb3adb.png)

**Comment by OroArmor** [comment]
this is an optifine issue and im not going to spend time trying to fix it
