### ISSUE TITLE
[Fabric] - Lava vision effect name

### ISSUE THREAD

**Issue by srnyx** [OroArmor/Netherite-Plus-Mod#93]
**Describe the bug**
The name for the lava vision effect shows up as effect.netherite_plus.lava_vision

**Expected behavior**
The effect should be shown as Lava Vision

**Screenshots**
![image](https://user-images.githubusercontent.com/25808801/111826068-9fbc1780-88be-11eb-89f8-4a0873c3f475.png)

**Comment by OroArmor** [comment]
Yep. Will be fixed in the next release

**Comment by srnyx** [comment]
> Yep. Will be fixed in the next release

Alright, thanks!
