### ISSUE TITLE
[Fabric][1.16.5] Add compatibility for [See Through Lava/Water]

### ISSUE THREAD

**Issue by Intezium** [OroArmor/Netherite-Plus-Mod#96]
**What is the mod and for which platform is it for**
This mod allows setting fog density for water/lava.

**What feature(s) is in conflict**
Fog density doesn't work for lava.

**Comment by OroArmor** [comment]
Could you provide screen shots?

**Comment by Intezium** [comment]
> Could you provide screen shots?

Install Netherite Plus:
![2021-03-26_23 06 35](https://user-images.githubusercontent.com/20191322/112687052-f3fb6480-8e87-11eb-9c64-097a15e15f72.png)


Uninstall Netherite Plus:
![2021-03-26_23 04 49](https://user-images.githubusercontent.com/20191322/112687070-f8278200-8e87-11eb-9ac7-cd036ffd12d1.png)
