### ISSUE TITLE
Add compatibility for barritone

### ISSUE THREAD

**Issue by energy11a** [OroArmor/Netherite-Plus-Mod#97]
**What is the mod and for which platform is it for** netheriteplus1.4.2 fabric

**What feature(s) is in conflict** barritone(meteor)
[crash-2021-03-27_17.13.11-client.txt](https://github.com/OroArmor/Netherite-Plus-Mod/files/6215887/crash-2021-03-27_17.13.11-client.txt)
Crashes when stepping on netherite shulkerbox

**Comment by OroArmor** [comment]
Won't support hacked clients or cheats sorry.

**Comment by energy11a** [comment]
it fails with barritone

**Comment by OroArmor** [comment]
Don't care. I won't fix the issue
