### ISSUE TITLE
[Forge] - Bug Netherite triden

### ISSUE THREAD

**Issue by NoDreamsRemain** [OroArmor/Netherite-Plus-Mod#98]
**Describe the bug**
Netherite trident rendering bug

**To Reproduce**
I crafted the netherite trident and i wanted to test it. But i couldn't see it. So i pressed F5 and i could see it but really small

**Screenshots**
![image](https://user-images.githubusercontent.com/77308088/112844345-02a96d80-907a-11eb-9bdb-b034bac623e6.png)
(note; it renders out of the hand)

**Comment by NoDreamsRemain** [comment]
pls help me

**Comment by OroArmor** [comment]
Duplicate of #82
